/**
 * Panel names — the single source of truth for what each section is called in the
 * sidebar, command palette, desk links and section headers. Standard industry terms;
 * no vendor or fund-brand names (methodology references cite the academic papers).
 * Keys are the stable section anchor ids (unchanged, so links and shortcuts keep working).
 */
export const PANEL_LABELS: Record<string, string> = {
  // Overview
  'my-desk': 'My Desk',
  'macro-model': 'Macro Model',
  'morning-brief': 'Daily Brief',
  'master-signal': 'Composite Signal',
  'key-metrics': 'Macro Indicators',
  anomalies: 'Anomaly Monitor',
  regime: 'Signal Regime',
  'regime-playbook': 'Regime Allocation',
  'market-clock': 'Market Hours',
  'global-markets': 'Global Equity Markets',
  'global-correlation': 'Global Equity Correlations',
  'regional-macro': 'Global Macro',
  'stock-ideas': 'Stock Ideas',
  'stock-timing': 'Stock Entry Signals',
  'stock-backtest': 'Entry Model Backtest',
  portfolios: 'Portfolios',
  'strategy-lab': 'Strategy Lab',
  // Signals
  ensemble: 'Model Ensemble',
  'signal-stack': 'Signal Breakdown',
  'signal-scorecard': 'Signal Performance',
  'signal-story': 'Signal Attribution',
  signals: 'Signal Detail',
  'alt-data': 'Alternative Data',
  'stream-agreement': 'Signal Agreement',
  'factor-validation': 'Factor Out-of-Sample Tests',
  'model-agreement': 'Model Agreement',
  'sector-allocation': 'Sector Allocation',
  'factor-rotation': 'Factor Performance',
  'cot-positioning': 'CFTC Positioning',
  'cta-trend': 'Trend-Following Signals',
  'news-sentiment': 'News Sentiment',
  'pure-alpha': 'Relative Momentum',
  // Risk
  'fund-cockpit': 'Fund Overview',
  'cycle-risk': 'Cycle & Systemic Risk',
  'risk-indicators': 'Risk Indicators',
  'risk-analytics': 'Risk Analytics',
  'var-stress': 'VaR & Stress Testing',
  'factor-exposure': 'Factor Exposure',
  'horizon-tension': 'Horizon Divergence',
  correlation: 'Stock–Bond Correlation',
  'correlation-matrix': 'Cross-Asset Correlation',
  'debt-cycle': 'Debt & Credit Cycle',
  'factor-decomposition': 'Factor Decomposition',
  'risk-parity': 'Risk Parity',
  'risk-parity-compare': 'Risk Parity Comparison',
  advanced: 'Leading Indicators',
  // Forecasts
  valuation: 'Valuation',
  nowcast: 'GDP Nowcast',
  'yield-curve': 'Yield Curve',
  liquidity: 'Financial Conditions',
  sentiment: 'Market Sentiment',
  'expected-returns': 'Expected Returns',
  'gmo-forecasts': 'Long-Run Return Assumptions',
  'regime-transition': 'Regime Transition Matrix',
  'regime-outlook': 'Regime Outlook',
  quadrants: 'Growth/Inflation Quadrants',
  'event-vol': 'Event Volatility',
  // Trading
  'trade-ideas': 'Trade Ideas',
  'trade-recommendations': 'Allocation Recommendations',
  'trade-workflow': 'Pre-Trade Analysis',
  'scenario-analysis': 'Scenario Analysis',
  'momentum-veto': 'Momentum Filter',
  // Portfolio
  'portfolio-positions': 'Positions',
  portfolio: 'Model Portfolio',
  'performance-attribution': 'Performance Attribution',
  'equity-research': 'Equity Research',
  'business-layer': 'Strategy Summary',
  'fx-monitor': 'FX',
  'commodities-dashboard': 'Commodities',
  'fixed-income-dashboard': 'Fixed Income',
  international: 'Regional Equity Regimes',
  reflexivity: 'Cross-Asset Feedback Loops',
  transmission: 'Policy Transmission',
  // System
  'economic-calendar': 'Economic Calendar',
  'data-to-watch': 'Upcoming Releases',
  'investment-memo': 'Investment Memo',
  'system-health': 'System Health',
  'data-providers': 'Data Providers',
  'system-audit': 'Audit & Compliance',
  'data-explorer': 'Data Explorer',
};

export const panelLabel = (id: string, fallback?: string) => PANEL_LABELS[id] ?? fallback ?? id;
