// Stock Ideas — suggestions generated by the system: the S&P 500 is screened on price
// (trend, momentum, 52-week high, entry timing), the strongest set-ups get the full entry
// model (earnings, sell-side, quality, levels), and the result is a sector-capped list of
// "buy now" and "buy on pullback" ideas with a running track record. api/stock_ideas.py.

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Lightbulb, Loader2, RefreshCw } from 'lucide-react';
import { cn } from '@/lib/utils';

const px = (v: number | null | undefined) => (v == null ? '—' : v.toLocaleString(undefined, { maximumFractionDigits: 2 }));
const pct = (v: number | null | undefined, d = 0) => (v == null ? '—' : `${(v * 100).toFixed(d)}%`);
const spct = (v: number | null | undefined, d = 1) => (v == null ? '—' : `${v >= 0 ? '+' : ''}${(v * 100).toFixed(d)}%`);

/** Open a symbol in the Stock Entry Signals panel. */
export function openStockAnalysis(symbol: string) {
  window.dispatchEvent(new CustomEvent('stock-analyse', { detail: symbol }));
}

export function StockIdeasSection() {
  const [data, setData] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);
  const [sector, setSector] = useState('All');

  const load = useCallback(async () => {
    try {
      const r = await fetch('/api/v1/stock/ideas');
      const j = await r.json();
      if (!r.ok) throw new Error(typeof j?.detail === 'string' ? j.detail : `HTTP ${r.status}`);
      setData(j); setError(null);
    } catch (e: any) { setError(e?.message || 'Unavailable'); }
  }, []);

  useEffect(() => { load(); }, [load]);
  // While a build runs, poll until it finishes.
  useEffect(() => {
    if (!data?.status?.running) return;
    const t = setInterval(load, 8000);
    return () => clearInterval(t);
  }, [data?.status?.running, load]);

  const refresh = async () => {
    await fetch('/api/v1/stock/ideas/refresh', { method: 'POST' }).catch(() => {});
    setData((d: any) => ({ ...(d ?? {}), status: { running: true } }));
    setTimeout(load, 1500);
  };

  const sectors = useMemo(() => ['All', ...Array.from(new Set([...(data?.buy ?? []), ...(data?.pullback ?? [])].map((r: any) => r.sector)))].filter(Boolean), [data]);
  const buy = (data?.buy ?? []).filter((r: any) => sector === 'All' || r.sector === sector);
  const pullback = (data?.pullback ?? []).filter((r: any) => sector === 'All' || r.sector === sector);
  const running = data?.status?.running;
  const tr = data?.track_record;

  return (
    <div className="terminal-section">
      <div className="section-header mb-3">
        <div className="section-header-left">
          <span className="section-tag"><Lightbulb className="w-3 h-3" /></span>
          <h2 className="section-title">Stock Ideas</h2>
          {data?.available && (
            <span className="text-2xs text-text-tertiary font-mono">
              {data.universe} · {data.screened} screened → {data.stage2} analysed · {new Date(data.as_of).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' })}
            </span>
          )}
        </div>
        <button onClick={refresh} disabled={running} title="Re-screen the S&P 500 now"
          className="inline-flex items-center gap-1 px-2 py-0.5 text-2xs border border-border text-text-secondary hover:text-bloomberg disabled:opacity-60">
          {running ? <Loader2 className="w-3 h-3 animate-spin" /> : <RefreshCw className="w-3 h-3" />}
          {running ? `Screening… ${data?.status?.running_for_s ?? 0}s` : 'Re-screen'}
        </button>
      </div>

      {error && <div className="p-2 text-xs text-amber border border-amber/30">{error}</div>}
      {data && !data.available && (
        <div className="p-4 text-xs text-text-secondary border border-border-subtle flex items-center gap-2">
          <Loader2 className="w-3.5 h-3.5 animate-spin" />{data.reason}
        </div>
      )}

      {data?.available && (
        <div className="space-y-2">
          {/* Context */}
          <div className="flex flex-wrap items-center gap-x-4 gap-y-1 px-3 py-2 bg-surface-1 border border-border text-2xs">
            <span className={data.market?.ok ? 'text-green' : 'text-amber'}>
              Market {data.market?.ok ? 'supportive' : 'unfavourable — size down'}
            </span>
            {data.breadth_above_200d != null && <span className="text-text-secondary">Breadth: <span className="font-mono text-text-primary">{pct(data.breadth_above_200d)}</span> of S&amp;P 500 above 200-day</span>}
            <span className="text-text-secondary">Strongest sectors: <span className="text-text-primary">{(data.sector_counts ?? []).slice(0, 3).map((s: any) => s.sector).join(' · ')}</span></span>
            {data.changes && (data.changes.new.length > 0 || data.changes.dropped.length > 0) && (
              <span className="text-text-secondary">
                {data.previous_date ? `vs ${data.previous_date}: ` : ''}
                {data.changes.new.length > 0 && <span className="text-green">new {data.changes.new.join(', ')}</span>}
                {data.changes.dropped.length > 0 && <span className="text-text-tertiary"> · dropped {data.changes.dropped.join(', ')}</span>}
              </span>
            )}
            <select value={sector} onChange={(e) => setSector(e.target.value)} aria-label="Sector filter"
              className="ml-auto bg-bg border border-border px-1.5 py-0.5 text-2xs text-text-secondary">
              {sectors.map((s) => <option key={s} value={s}>{s}</option>)}
            </select>
          </div>

          {/* Buy now */}
          <div>
            <div className="text-2xs text-text-tertiary uppercase tracking-wider mb-1.5">Buy now — set-up and entry aligned ({buy.length})</div>
            {buy.length === 0 ? <div className="p-3 text-2xs text-text-tertiary border border-border-subtle">No stock passes every test today{sector !== 'All' ? ' in this sector' : ''}.</div> : (
              <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-2">
                {buy.map((r: any) => (
                  <div key={r.symbol} className="p-3 bg-surface-1 border border-border border-l-2 border-l-green flex flex-col">
                    <div className="flex items-baseline gap-2">
                      <span className="font-mono text-sm font-bold text-text-primary">{r.symbol}</span>
                      <span className="text-2xs text-text-secondary truncate">{r.name}</span>
                      <span className="ml-auto font-mono text-xs text-text-primary">{px(r.price)}</span>
                    </div>
                    <div className="flex items-center gap-2 mt-0.5">
                      <span className="text-[10px] text-text-tertiary">{r.sector}</span>
                      <span className="ml-auto text-[10px] text-text-tertiary">set-up</span>
                      <div className="w-16 h-1.5 bg-surface-3"><div className="h-1.5 bg-green/70" style={{ width: `${Math.max(0, r.setup_score) * 100}%` }} /></div>
                      <span className="font-mono text-2xs">{r.setup_score?.toFixed(2)}</span>
                    </div>
                    <div className="flex flex-wrap gap-1 mt-2">
                      {(r.rationale ?? []).map((x: string) => <span key={x} className="px-1.5 py-0.5 text-[10px] bg-surface-3 text-text-secondary">{x}</span>)}
                      {(r.risks ?? []).map((x: string) => <span key={x} className="px-1.5 py-0.5 text-[10px] border border-amber/40 text-amber">{x}</span>)}
                    </div>
                    <div className="grid grid-cols-4 gap-1 mt-2 text-[10px] font-mono">
                      <div><div className="text-text-tertiary font-sans">Entry</div>{px(r.entry_low)}–{px(r.entry_high)}</div>
                      <div><div className="text-text-tertiary font-sans">Stop</div><span className="text-red">{px(r.stop)}</span></div>
                      <div title={r.target_basis}><div className="text-text-tertiary font-sans">Target</div><span className="text-green">{px(r.target)}</span></div>
                      <div><div className="text-text-tertiary font-sans">R:R · size</div>{r.reward_risk ?? '—'} · {pct(r.pct_nav, 1)}</div>
                    </div>
                    <button onClick={() => openStockAnalysis(r.symbol)} className="mt-2 self-start text-2xs text-bloomberg hover:underline">Full analysis →</button>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Pullback list */}
          {pullback.length > 0 && (
            <div className="p-3 bg-surface-1 border border-border">
              <div className="text-2xs text-text-tertiary uppercase tracking-wider mb-1">Buy on pullback — strong set-up, wait for the entry ({pullback.length})</div>
              <div className="overflow-x-auto">
                <table className="w-full text-xs font-mono">
                  <thead><tr className="text-2xs text-text-tertiary text-left font-sans">
                    <th className="font-normal pb-1">Stock</th><th className="font-normal">Why wait</th><th className="font-normal text-right">Set-up</th>
                    <th className="font-normal text-right">Price</th><th className="font-normal text-right">Entry zone</th><th className="font-normal text-right">Away</th><th className="font-normal text-right">R:R at zone</th></tr></thead>
                  <tbody>
                    {pullback.map((r: any) => {
                      const away = r.entry_high && r.price ? r.entry_high / r.price - 1 : null;
                      return (
                        <tr key={r.symbol} onClick={() => openStockAnalysis(r.symbol)} className="border-t border-border-subtle cursor-pointer hover:bg-surface-2">
                          <td className="py-1"><span className="text-text-primary">{r.symbol}</span> <span className="font-sans text-[10px] text-text-tertiary">{r.sector}</span></td>
                          <td className="font-sans text-2xs text-amber">{r.verdict_label.replace('Buy candidate — ', '')}</td>
                          <td className="text-right">{r.setup_score?.toFixed(2)}</td>
                          <td className="text-right">{px(r.price)}</td>
                          <td className="text-right">{px(r.entry_low)}–{px(r.entry_high)}</td>
                          <td className="text-right text-text-secondary">{spct(away)}</td>
                          <td className="text-right">{r.reward_risk ?? '—'}</td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Track record */}
          <div className="px-3 py-2 bg-surface-1 border border-border text-2xs text-text-secondary">
            <span className="text-text-tertiary uppercase tracking-wider mr-2">Track record</span>
            {tr?.ideas ? (
              <>past buy ideas since {tr.since}: <span className="font-mono text-text-primary">{tr.ideas}</span> ·
                avg return <span className="font-mono text-text-primary">{spct(tr.avg_return)}</span> ·
                vs S&amp;P 500 <span className={cn('font-mono', tr.avg_excess >= 0 ? 'text-green' : 'text-red')}>{spct(tr.avg_excess)}</span> ·
                beat the index <span className="font-mono text-text-primary">{pct(tr.beat_spx)}</span></>
            ) : <span className="text-text-tertiary">{tr?.message ?? '—'}</span>}
          </div>

          <div className="text-[10px] text-text-tertiary">
            Method: every S&amp;P 500 stock is scored on trend, volatility-scaled momentum and 52-week-high proximity; the strongest {data.stage2} get the full
            entry model (earnings drift, sell-side consensus and revisions, quality, entry timing, levels). At most three ideas per sector. Rebuilt after
            each US close. Suggestions are systematic and probabilistic — not investment advice.
          </div>
        </div>
      )}
    </div>
  );
}
