// Stock Ideas — suggestions generated by the system across the global universe: ~3,000 of the
// largest stocks in 45 markets (MSCI Developed, Emerging, Frontier, Standalone) are screened on
// price, the strongest set-ups per market class get the full entry model, and the result is a
// country- and sector-capped list of "buy now" and "buy on pullback" ideas, filterable by
// market class, region, country and sector, with a USD track record vs MSCI ACWI.

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Lightbulb, Loader2, RefreshCw, Star } from 'lucide-react';
import { cn } from '@/lib/utils';
import { marketTag, marketTitle } from '@/lib/marketTag';

const px = (v: number | null | undefined) => (v == null ? '—' : v.toLocaleString(undefined, { maximumFractionDigits: 2 }));
const pct = (v: number | null | undefined, d = 0) => (v == null ? '—' : `${(v * 100).toFixed(d)}%`);
const spct = (v: number | null | undefined, d = 1) => (v == null ? '—' : `${v >= 0 ? '+' : ''}${(v * 100).toFixed(d)}%`);
const usdM = (v: number | null | undefined) => (v == null ? '—' : v >= 1e6 ? `$${(v / 1e6).toFixed(2)}M` : `$${Math.round(v / 1e3)}K`);
const CLASSES = ['All', 'Developed', 'Emerging', 'Frontier', 'Standalone'];
const CLASS_TONE: Record<string, string> = {
  Developed: 'border-[#3987e5]/50 text-[#3987e5]', Emerging: 'border-[#c98500]/50 text-[#c98500]',
  Frontier: 'border-[#199e70]/50 text-[#199e70]', Standalone: 'border-border text-text-tertiary',
};

/** Open a symbol in the Stock Entry Signals panel. */
export function openStockAnalysis(symbol: string) {
  window.dispatchEvent(new CustomEvent('stock-analyse', { detail: symbol }));
}

function MarketTag({ r }: { r: any }) {
  return (
    <span className={cn('px-1 border text-[10px] font-mono whitespace-nowrap', CLASS_TONE[r.market_class] ?? 'border-border text-text-tertiary')}
      title={marketTitle(r)}>
      {marketTag(r)}
    </span>
  );
}

export function StockIdeasSection() {
  const [data, setData] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);
  const [cls, setCls] = useState('All');
  const [region, setRegion] = useState('All');
  const [country, setCountry] = useState('All');
  const [sector, setSector] = useState('All');
  const [showBreadth, setShowBreadth] = useState(false);

  const load = useCallback(async () => {
    try {
      const r = await fetch('/api/v1/stock/ideas');
      const j = await r.json();
      if (!r.ok) throw new Error(typeof j?.detail === 'string' ? j.detail : `HTTP ${r.status}`);
      setData(j); setError(null);
    } catch (e: any) { setError(e?.message || 'Unavailable'); }
  }, []);

  useEffect(() => { load(); }, [load]);
  useEffect(() => {
    if (!data?.status?.running) return;
    const t = setInterval(load, 8000);
    return () => clearInterval(t);
  }, [data?.status?.running, load]);

  const refresh = async () => {
    await fetch('/api/v1/stock/ideas/refresh', { method: 'POST' }).catch(() => {});
    setData((d: any) => ({ ...(d ?? {}), status: { running: true } }));
    setTimeout(load, 1500);
  };

  const all = useMemo(() => [...(data?.buy ?? []), ...(data?.pullback ?? [])], [data]);
  const opts = (key: string, base: any[] = all) => ['All', ...Array.from(new Set(base.map((r: any) => r[key]).filter(Boolean))).sort()];
  const match = (r: any) => (cls === 'All' || r.market_class === cls) && (region === 'All' || r.region === region)
    && (country === 'All' || r.country === country) && (sector === 'All' || r.sector === sector);
  const buy = (data?.buy ?? []).filter(match);
  const pullback = (data?.pullback ?? []).filter(match);
  const running = data?.status?.running;
  const tr = data?.track_record;
  const countryName = (c: string) => (data?.by_country ?? []).find((x: any) => x.key === c)?.name ?? c;

  const Select = ({ value, set, options, label, render }: { value: string; set: (v: string) => void; options: string[]; label: string; render?: (v: string) => string }) => (
    <select value={value} onChange={(e) => set(e.target.value)} aria-label={label}
      className="bg-bg border border-border px-1.5 py-0.5 text-2xs text-text-secondary max-w-[11rem]">
      {options.map((o) => <option key={o} value={o}>{o === 'All' ? `${label}: all` : render ? render(o) : o}</option>)}
    </select>
  );

  return (
    <div className="terminal-section">
      <div className="section-header mb-3">
        <div className="section-header-left">
          <span className="section-tag"><Lightbulb className="w-3 h-3" /></span>
          <h2 className="section-title">Stock Ideas</h2>
          {data?.available && (
            <span className="text-2xs text-text-tertiary font-mono">
              {data.screened?.toLocaleString()} stocks · {(data.by_country ?? []).length} markets screened → {data.stage2} analysed ·{' '}
              {new Date(data.as_of).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' })}
            </span>
          )}
        </div>
        <button onClick={refresh} disabled={running} title="Re-screen the global universe now"
          className="inline-flex items-center gap-1 px-2 py-0.5 text-2xs border border-border text-text-secondary hover:text-bloomberg disabled:opacity-60">
          {running ? <Loader2 className="w-3 h-3 animate-spin" /> : <RefreshCw className="w-3 h-3" />}
          {running ? `Screening… ${data?.status?.running_for_s ?? 0}s` : 'Re-screen'}
        </button>
      </div>

      {error && <div className="p-2 text-xs text-amber border border-amber/30">{error}</div>}
      {data && !data.available && (
        <div className="p-4 text-xs text-text-secondary border border-border-subtle flex items-center gap-2">
          <Loader2 className="w-3.5 h-3.5 animate-spin" />{data.reason}
        </div>
      )}

      {data?.available && (
        <div className="space-y-2">
          {/* Context + filters */}
          <div className="px-3 py-2 bg-surface-1 border border-border space-y-1.5">
            <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-2xs">
              <span className={data.market?.ok ? 'text-green' : 'text-amber'}>Global market (MSCI ACWI) {data.market?.ok ? 'supportive' : 'unfavourable'}</span>
              <span className="text-text-secondary">Breadth above 200-day:{' '}
                {(data.by_class ?? []).filter((g: any) => g.names >= 10).map((g: any) => (
                  <span key={g.key} className="mr-2"><span className="text-text-tertiary">{g.key}</span> <span className="font-mono text-text-primary">{pct(g.above_200d)}</span></span>
                ))}
              </span>
              <button onClick={() => setShowBreadth((s) => !s)} className="text-text-tertiary hover:text-bloomberg underline-offset-2 hover:underline">
                {showBreadth ? 'hide' : 'by region & country'}
              </button>
              {data.changes && (data.changes.new.length > 0 || data.changes.dropped.length > 0) && (
                <span className="text-text-secondary">
                  {data.previous_date ? `vs ${data.previous_date}: ` : ''}
                  {data.changes.new.length > 0 && <span className="text-green">new {data.changes.new.slice(0, 8).join(', ')}{data.changes.new.length > 8 ? '…' : ''}</span>}
                  {data.changes.dropped.length > 0 && <span className="text-text-tertiary"> · dropped {data.changes.dropped.slice(0, 6).join(', ')}</span>}
                </span>
              )}
            </div>
            <div className="flex flex-wrap items-center gap-1.5">
              <div className="flex border border-border" role="tablist" aria-label="Market class">
                {CLASSES.map((c) => (
                  <button key={c} role="tab" aria-selected={cls === c} onClick={() => { setCls(c); setCountry('All'); }}
                    className={cn('px-2 py-0.5 text-2xs', cls === c ? 'bg-bloomberg text-bg' : 'text-text-secondary hover:text-text-primary')}>{c}</button>
                ))}
              </div>
              <Select value={region} set={(v) => { setRegion(v); setCountry('All'); }} options={opts('region')} label="Region" />
              <Select value={country} set={setCountry} label="Country"
                options={opts('country', all.filter((r: any) => (cls === 'All' || r.market_class === cls) && (region === 'All' || r.region === region)))}
                render={(c) => `${countryName(c)} (${c})`} />
              <Select value={sector} set={setSector} options={opts('sector')} label="Sector" />
            </div>
            {showBreadth && (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-1 text-[10px] font-mono">
                <table className="w-full"><thead><tr className="text-text-tertiary text-left font-sans"><th className="font-normal">Region</th><th className="font-normal text-right">Stocks</th><th className="font-normal text-right">&gt; 200d</th><th className="font-normal text-right">Strong set-ups</th></tr></thead>
                  <tbody>{(data.by_region ?? []).map((g: any) => <tr key={g.key} className="border-t border-border-subtle"><td className="font-sans text-text-secondary">{g.key}</td><td className="text-right">{g.names}</td><td className="text-right">{pct(g.above_200d)}</td><td className="text-right">{g.strong}</td></tr>)}</tbody></table>
                <table className="w-full"><thead><tr className="text-text-tertiary text-left font-sans"><th className="font-normal">Strongest markets</th><th className="font-normal text-right">Stocks</th><th className="font-normal text-right">&gt; 200d</th><th className="font-normal text-right">Avg set-up</th></tr></thead>
                  <tbody>{(data.by_country ?? []).filter((g: any) => g.names >= 8).slice(0, 10).map((g: any) => (
                    <tr key={g.key} className="border-t border-border-subtle cursor-pointer hover:bg-surface-2" onClick={() => { setCls('All'); setRegion('All'); setCountry(g.key); }}>
                      <td className="font-sans text-text-secondary">{g.name}</td><td className="text-right">{g.names}</td><td className="text-right">{pct(g.above_200d)}</td><td className="text-right">{g.avg_setup == null ? '—' : g.avg_setup.toFixed(2)}</td></tr>))}</tbody></table>
              </div>
            )}
          </div>

          {/* Buy now */}
          <div>
            <div className="text-2xs text-text-tertiary uppercase tracking-wider mb-1.5">Buy now — set-up and entry aligned ({buy.length})</div>
            {buy.length === 0 ? <div className="p-3 text-2xs text-text-tertiary border border-border-subtle">No stock passes every test for this filter today.</div> : (
              <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-2">
                {buy.slice(0, 24).map((r: any) => (
                  <div key={r.symbol} className="p-3 bg-surface-1 border border-border border-l-2 border-l-green flex flex-col">
                    <div className="flex items-baseline gap-2">
                      <span className="font-mono text-sm font-bold text-text-primary">{r.symbol}</span>
                      <span className="text-2xs text-text-secondary truncate">{r.name}</span>
                      <span className="ml-auto font-mono text-xs text-text-primary whitespace-nowrap">{px(r.price)} <span className="text-[10px] text-text-tertiary">{r.currency}</span></span>
                    </div>
                    <div className="flex items-center gap-2 mt-0.5">
                      <MarketTag r={r} />
                      <span className="text-[10px] text-text-tertiary truncate">{r.sector ?? '—'}</span>
                      {r.watchlist && <Star className="w-3 h-3 text-amber" fill="currentColor" aria-label="On your watchlist" />}
                      <span className="ml-auto text-[10px] text-text-tertiary">set-up</span>
                      <div className="w-14 h-1.5 bg-surface-3"><div className="h-1.5 bg-green/70" style={{ width: `${Math.max(0, r.setup_score) * 100}%` }} /></div>
                      <span className="font-mono text-2xs">{r.setup_score?.toFixed(2)}</span>
                    </div>
                    <div className="flex flex-wrap gap-1 mt-2">
                      {(r.rationale ?? []).map((x: string) => <span key={x} className="px-1.5 py-0.5 text-[10px] bg-surface-3 text-text-secondary">{x}</span>)}
                      {(r.risks ?? []).map((x: string) => <span key={x} className="px-1.5 py-0.5 text-[10px] border border-amber/40 text-amber">{x}</span>)}
                    </div>
                    <div className="grid grid-cols-4 gap-1 mt-2 text-[10px] font-mono">
                      <div><div className="text-text-tertiary font-sans">Entry</div>{px(r.entry_low)}–{px(r.entry_high)}</div>
                      <div><div className="text-text-tertiary font-sans">Stop</div><span className="text-red">{px(r.stop)}</span></div>
                      <div title={r.target_basis}><div className="text-text-tertiary font-sans">Target</div><span className="text-green">{px(r.target)}</span></div>
                      <div title="Reward:risk · size in USD (% of NAV)"><div className="text-text-tertiary font-sans">R:R · size</div>{r.reward_risk ?? '—'} · {usdM(r.notional_usd)}</div>
                    </div>
                    <button onClick={() => openStockAnalysis(r.symbol)} className="mt-2 self-start text-2xs text-bloomberg hover:underline">Full analysis →</button>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Pullback list */}
          {pullback.length > 0 && (
            <div className="p-3 bg-surface-1 border border-border">
              <div className="text-2xs text-text-tertiary uppercase tracking-wider mb-1">Buy on pullback — strong set-up, wait for the entry ({pullback.length})</div>
              <div className="overflow-x-auto">
                <table className="w-full text-xs font-mono">
                  <thead><tr className="text-2xs text-text-tertiary text-left font-sans">
                    <th className="font-normal pb-1">Stock</th><th className="font-normal">Market</th><th className="font-normal">Why wait</th><th className="font-normal text-right">Set-up</th>
                    <th className="font-normal text-right">Price</th><th className="font-normal text-right">Entry zone</th><th className="font-normal text-right">Away</th></tr></thead>
                  <tbody>
                    {pullback.slice(0, 30).map((r: any) => {
                      const away = r.entry_high && r.price ? r.entry_high / r.price - 1 : null;
                      return (
                        <tr key={r.symbol} onClick={() => openStockAnalysis(r.symbol)} className="border-t border-border-subtle cursor-pointer hover:bg-surface-2">
                          <td className="py-1"><span className="text-text-primary">{r.symbol}</span> <span className="font-sans text-[10px] text-text-tertiary">{(r.name ?? '').slice(0, 26)}</span></td>
                          <td><MarketTag r={r} /></td>
                          <td className="font-sans text-2xs text-amber">{String(r.verdict_label).replace('Buy candidate — ', '')}</td>
                          <td className="text-right">{r.setup_score?.toFixed(2)}</td>
                          <td className="text-right">{px(r.price)} <span className="text-[10px] text-text-tertiary">{r.currency}</span></td>
                          <td className="text-right">{px(r.entry_low)}–{px(r.entry_high)}</td>
                          <td className="text-right text-text-secondary">{spct(away)}</td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Watchlist */}
          {(data.watchlist ?? []).length > 0 && (
            <div className="px-3 py-2 bg-surface-1 border border-border text-2xs">
              <span className="text-text-tertiary uppercase tracking-wider mr-2">Your watchlist</span>
              {data.watchlist.map((w: any) => (
                <button key={w.symbol} onClick={() => openStockAnalysis(w.symbol)} className="mr-3 hover:underline">
                  <span className="font-mono text-text-primary">{w.symbol}</span>{' '}
                  <span className={w.verdict === 'BUY' ? 'text-green' : w.verdict === 'AVOID' ? 'text-red' : 'text-amber'}>{w.verdict}</span>
                </button>
              ))}
            </div>
          )}

          {/* Track record */}
          <div className="px-3 py-2 bg-surface-1 border border-border text-2xs text-text-secondary">
            <span className="text-text-tertiary uppercase tracking-wider mr-2">Track record (USD)</span>
            {tr?.ideas ? (
              <>past buy ideas since {tr.since}: <span className="font-mono text-text-primary">{tr.ideas}</span> ·
                avg return <span className="font-mono text-text-primary">{spct(tr.avg_return)}</span> ·
                vs MSCI ACWI <span className={cn('font-mono', tr.avg_excess >= 0 ? 'text-green' : 'text-red')}>{spct(tr.avg_excess)}</span> ·
                beat the index <span className="font-mono text-text-primary">{pct(tr.beat_spx)}</span></>
            ) : <span className="text-text-tertiary">{tr?.message ?? '—'}</span>}
          </div>

          <div className="text-[10px] text-text-tertiary">
            Universe: the largest stocks of each market on its primary exchange (Yahoo screener), one listing per company, classified by
            MSCI market class; rebuilt weekly. Every stock is scored on trend, volatility-scaled momentum and 52-week-high proximity; the
            strongest set-ups per market class get the full entry model. Prices in local currency, sizes in USD. Any other listed stock can
            be analysed from Stock Entry Signals or added to your watchlist. Systematic and probabilistic — not investment advice.
          </div>
        </div>
      )}
    </div>
  );
}
